CREATE DATABASE contacts;

USE contacts;

CREATE TABLE info (
NAME VARCHAR(30) NOT NULL,
phone VARCHAR(30) NOT NULL,
email VARCHAR(50),
gender VARCHAR(50),
dob VARCHAR(50),
country VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
SELECT * FROM info;


